### PR TITLE
adds to readme

### PR DESCRIPTION
**Pull request by iamvs-2002**
This is my contribution.

### CODE REVIEW

**Comment by vczh** [comment]
I doubt that is π≈22/7 is clear to all people or not, since this is a show case, it doesn't actually care about the precision.

**Comment by iam2002** [comment]
> I doubt that is π≈22/7 is clear to all people or not, since this is a show case, it doesn't actually care about the precision.

Yes, but I, being a student of mathematics, is being taught that it is better to have as much accuracy as possible.

**Comment by hczhcz** [comment]
`22/7` (a division between two integers) does not "look like" an approximate value from a perspective of semantic.

**Comment by iamvs-2002** [comment]
Plz accept my pull request. I wanna win Hacktoberfest.

**Pull request merged**
